[package]
name = "using_channels_signal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5"
anyhow = "1.0"
ctrlc = "3.2" 
